### ISSUE TITLE
Run file

### ISSUE THREAD

**Issue by rosanerofan** [pcjedi/ryanair#1]
I can't run the script because I receive the following error:
line 135 , in <module> assert args.root_origin in a AssertionError

How can be fixed it ?

**Comment by pcjedi** [comment]
Hi, 

the root_origin must be a ryanair airport code. Specifically on of: https://www.ryanair.com/api/locate/v1/autocomplete/airports

I refactored the code so that it is now more clear on how to fix this error when it occurs.

**Comment by rosanerofan** [comment]
Thanks for the update
